firebase.apiKey=apikey
firebase.authDomain=domain
firebase.projectId=project_id
firebase.storageBucket=storage
firebase.messagingSenderId=messagingSenderId
firebase.appId=appId
firebase.measurementId=measurementId
