firebase.apiKey=AIzaSyAO-J_vldy8Luvu0BIn6fxZT7Nr4faXQkQ
firebase.authDomain=auth-d5edd.firebaseapp.com
firebase.projectId=auth-d5edd
firebase.storageBucket=auth-d5edd.appspot.com
firebase.messagingSenderId=394049645839
firebase.appId=1:394049645839:web:90f0b51c3fa0433247a27a
firebase.measurementId=G-1455LBJTCD